//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpRestfulService.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmpDbEntities : DbContext
    {
        public EmpDbEntities()
            : base("name=EmpDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EmployeeTable> EmployeeTables { get; set; }
        public DbSet<PhotoTable> PhotoTables { get; set; }
        public DbSet<SalaryTable> SalaryTables { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
